#!/bin/bash

# -q = QUIET , no muestra texto en pantalla

#VERIFICA SI LOS PROGRAMAS DEL ARREGLO ESTAN INSTALADOS 
#Y SI NO ESTAN, LOS INSTALA. 

green="\e[92m"
red="\e[91m"
default="\e[0m"
bold="\e[1m"
QUIET=0
t=0.1
toInstall=()

## (nameIn AptGet,NameForHash)
programs=(python,python python-pip,python-pip samba,samba openssh-server,sshd vsftpd,vsftpd git,git)

for p in $(seq 1 $#)
	do
		eval parametro='$'$p
		if [ $parametro == "-q" ]; then
			QUIET=1
		fi
	done
	
if [ ! $QUIET ];then
	clear
fi

msg(){
        if [ ${QUIET} -eq 0 ] ;then
                echo $@
        fi
}

msgConLinea(){
	start=$1
	linea="-----------------------------"
	msg -ne "$start ${linea[@]:$(expr length "$start")}"
}
	
checkIfInstalled(){
	msgConLinea "-$(echo "$1"|cut -d, -f1)"
	if ! hash $(echo "$1"|cut -d, -f2) 2>/dev/null; then 
			msg -ne "[${red}${bold}XX${default}]"
			toInstall[${#toInstall[@]}]=$1
			msg "<--add to Install"
	else
		msg -e "[${green}${bold}OK${default}]"
	fi
	sleep $t
}

instalar() {
	arr=$@
	for program in ${arr[@]} 
	do
			prog=$(echo "$program"|cut -d, -f1)
			msgConLinea "++++Instalando $prog"
			errn=$( { apt-get -y -q install $prog; } 2>&1)
			if [ $? -eq 0 ]; then
				msg -e "[${green}${bold}OK${default}]"
				
			else
				msg -e "[${red}${bold}ERROR${default}]"
			fi
	done

}


for program in "${programs[@]}"
	do
		checkIfInstalled $program
	done



if [ ! ${#toInstall[@]} -eq 0 ];then
	if ! [ $(id -u) = "0" ] 2>/dev/null; then
		echo -e "${red}${bold}You don't have admin privileges, i can't install the programs${default}"
		exit 1 
	fi
	msg ""
	msg -e "[]INSTALACION DE PROGRAMAS"
	instalar ${toInstall[@]}
fi

exit 0

